name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: subosito/flutter-action@master
      with:
        channel: master
    - run: flutter config --enable-linux-desktop
    - run: flutter pub get
    - run: flutter build linux
    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: build/linux/release/bundle/
